### ISSUE TITLE
Update repo description to "(Karma + Sassy) * (Facebook + Slack + Skype + Hipchat + Telegram) = Kassy"

### ISSUE THREAD

**Issue by phillipadsmith** [concierge/Concierge#180]
Repo description (high on the page, seen first) doesn't reflect the current platform support. Should be 

> (Karma + Sassy) * (Facebook + Slack + Skype + Hipchat + Telegram) = Kassy

**Comment by mrkno** [comment]
We probably just need to remove this entirely (or make it more consise) because Hubot adapters are semi-supported out of the box currently too, plus we will need to add Messenger, and MS Bots (soon anyway).

**Comment by phillipadsmith** [comment]
> We probably just need to remove this entirely (or make it more consise) because Hubot adapters are semi-supported out of the box currently too, plus we will need to add Messenger, and MS Bots (soon anyway).

Good point. Perhaps a new tagline entirely then, yes?

**Comment by ParasDPain** [comment]
Can we make it more user friendly while we are at it, so any non-IT person can understand it. It'd also be great if we can provide some kind of installer mechanism or something to broaden the target audience

**Comment by phillipadsmith** [comment]
> Can we make it more user friendly while we are at it, so any non-IT person can understand it.

Though I'm in favour of something "user friendly," I'm not sure non-IT people are the audience? 

> It'd also be great if we can provide some kind of installer mechanism or something to broaden the target audience

Broaden it to? I'm curious who you think might use something like this beyond fairly technical people? 

Phillip.

**Comment by ParasDPain** [comment]
A lot of my friends are interested in having their own bot but don't want to learn programming. If Kassy can be packaged into an installer and provide an interface to install modules, it'll solve their problems.

Of Course everyone has different expectations from the modules and Kassy itself but everyone wants their own personal-bot

**Comment by phillipadsmith** [comment]
> A lot of my friends are interested in having their own bot but don't want to learn programming.

Sure, I get that, and yet I don't think these people are going to be able to figure out Kassy very easily, i.e., where are they going to host it? How are they going to configure it? 

> If Kassy can be packaged into an installer and provide an interface to install modules, it'll solve their problems.

But maybe those are Kassy's problems? 

> Of Course everyone has different expectations from the modules and Kassy itself but everyone wants their own personal-bot

What about something like https://flowxo.com/ that is purpose-built for non-technical people?

**Comment by mrkno** [comment]
>  It'd also be great if we can provide some kind of installer mechanism or something to broaden the target audience

An installer would be nice, its something that could be generated as a build artifact by Travis on a master build. Remember that an installer would also need to install:
- A supported version of Node.js
- NPM if it wasn't packaged with Node.js
- Git for updates and module installs

Unfortunately I don't really have time amoungst the other improvements to Kassy and Life™ to investigate this currently.

> A lot of my friends are interested in having their own bot but don't want to learn programming

As in they want to host their own bot and install someone elses modules into it but do not want to create their own? I'm currently trying to patch Kassy to support an easy deploy to heuroku so that all that is needed is a series of copied and pasted commands to host your bot.

@phillipadsmith is right in saying that Kassy is reasonably easy to work out and that some technical knowledge will still probably be required because it needs to be hosted somewhere.

>  ... provide an interface to install modules

Of course it would always be possible to create a module for Kassy (currently a core one, soon not to be) which could manage Kassy itself. That way Kassy itself doesn't change but it is possible to install modules through some kind of GUI (I would suggest an express.js based GUI). This module could come pre-installed as a part of the installer mentioned.

All this being said, I wouldn't have said `/kpm install foo` was that hard even for the most technophobic people.

**Comment by phillipadsmith** [comment]
> because Hubot adapters are semi-supported out of the box currently too

Somehow I missed this. This is crazy-awesome. Can you say more?

**Comment by mrkno** [comment]
@phillipadsmith I will use the discord one as an example. In the current (non PR) version of Kassy you can do this:
```shell
cd core/core_integrations
git clone https://github.com/thetimpanist/hubot-discord.git
cd ../../
echo > config.json << EOF
{
    "output": {
        "hubot-discord": {
            "ENV_HUBOT_DISCORD_EMAIL":" <email/username>",
            "ENV_HUBOT_DISCORD_PASSWORD":"<secret password>",
            "ENV_HUBOT_DISCORD_TOKEN":"<oauth token>"
        }
    }
}
EOF

node main.js hubot-discord
```
This feature is currently not documented but is intended to be a stop-gap measure until a real integration can be created. Not all hubot adapters work, some only work on their second startup (no idea why) and some features of Kassy do not work properly (primarily shutdown and startup). We also support a good percentage of Hubot scripts out of the box too in case you wern't aware (also not documented).

Maybe in the distant future we might do something similar with botkit and some others as well given the required loading infrustructure is in place.

**Comment by phillipadsmith** [comment]
> We also support a good percentage of Hubot scripts out of the box too in case you wern't aware (also not documented).

Yes, I read that in an issue recently and my curiosity was piqued.  :-)

**Comment by Awarua-** [comment]
@mrkno Not sure what the purpose of this issue is now?
