### ISSUE TITLE
Download an image and send it to chat when it's url?

### ISSUE THREAD

**Issue by p0358** [concierge/Concierge#210]
I have an idea - if there's function call like this

``` javascript
api.sendImage("url", "http://example.com/image.jpg", "", event.thread_id);
```

to the facebook integration API (and maybe some others?), it could download the image and send it to the thread as an attachment instead of just sending the link. If someone wants to send a link instead of image, he can always use `sendMessage` function. I think it shouldn't be that hard to implement. There could be some checks to ensure the file to download is not too big.

**Comment by mrkno** [comment]
@p0358 this may fall into the category of API bloat, and would potentially open us up to a security valnerability. It is possible to use
```javascript
// don't quote me on this, I don't have the code in front of me
api.sendImage("file", <bytes>, "", event.thread_id);
```
and just download the image yourself within a module. I am also considering the implicatgions of adding some way to intercept incoming and outgoing messages to Concierge (such that you could write a module to translate it yourself if you wanted).

As it stands, the core of Concierge shouldn't have any major security valnerabilities because it doesn't care about what you receive, send, how or where it gets it from. If we start downloading images and then sending them as a byte-stream we open it up to someone creating a mallicious image file, which we then download and by loading it as a bytestream into memory, execute (if node.js ever has a buffer overflow valnerability it will be particularly easy to exploit). It is fine if this happens within a module - that is not our problem, it is the fault of the person who wrote the module.

There are other implications of the proposal:
- denial of service attacks: what if we start downloading millions of images
- storage: we need to store these either in memory or on the HD until they are sent. The V8 garbage collector may not collect them for some time causing a memory leak.
- speed: it could take quite some time to download an image. Presuming the URL is an HTTP url, we may be able to use a HEAD request to find the file size, but as of HTTP/1.1 that is optional and many sites do not conform to the origional spec.

**Comment by ParasDPain** [comment]
Could this functionality be delegated to an intercepting module/service that listens to all conversations? This would avoid modifications to the core and allow more control over the service itself.

The service can replace Concierge responses containing image links with images themselves.

PS: Facebook already attaches an image-preview to image links

**Comment by mrkno** [comment]
That was one of the ideas behind #217. Allow middleware so any input can be mutated into any output. Might also let us fix admin and disable

**Comment by p0358** [comment]
Yep, that was what I was thinking of as well. A module could use some external API to convert images and that would ensure us that we're getting proper image, not a malicious thing (I think/hope).
