### ISSUE TITLE
None of included modules work?

### ISSUE THREAD

**Issue by NekoKamiDesu** [concierge/Concierge#211]
All of the included modules don't work for me (e.g. ping, kpm) and when I send in a message (e.g !ping) I get no response and the console doesn't throw any errors in the console. Any ideas?
p.s. I'm using facebook integration.

**Comment by ParasDPain** [comment]
If you've updated to the latest version, have a look in the `modules` folder. You'll only be able to access modules installed there We've separated all modules into their own repos so by default none of them come packaged with the core application; to any access any you'll have to manually install them.

The immediate ones are available [here](https://github.com/concierge) I recommend starting with the [kpm](https://github.com/concierge) to installing others an ease.

**Comment by mrkno** [comment]
@NekoKamiDesu the documentation is a *little bit* [read: very] out of date which won't be helping.

If you have both git and npm available in your path the first run of Concierge should go off and install some default modules for you, such as `ping` and `kpm`. If these were not installed you will need to git clone them or otherwise install them into the modules directory for them to work. You can force the first-run install to run again by deleting this section from your `config.json` file:
```json
"firstRun": {
    "hasRun": true
}
```

On Facebook, the default prefix is '/' unless you have changed it in your config.json (see [here](https://github.com/concierge/Concierge/blob/master/doc/integrations/Facebook.md)) so `!ping` would actually be `/ping`.

**Comment by mrkno** [comment]
@NekoKamiDesu as your question has been answered I'm closing this. Reopen or create a new issue if you need further assistance.
