### ISSUE TITLE
package.json for modules

### ISSUE THREAD

**Issue by phillipadsmith** [concierge/Concierge#229]
Is there yet a way to include a package.json for a module and have that used when the module is installed via KPM? 

I ask because for a module I've written it requires some very specific dependencies (versions, forks, etc.) to be installed vs. just installing whatever `npm` finds from the require statements.

Anyway to handle this gracefully? 

Phillip.

**Comment by mrkno** [comment]
If you mean installing and using specific versions of npm dependencies within your module, the answer is currently no. The amount of work that would be required to support that is large, expecially when it is possible to use things like manual installs, code inclusion and git submodules.

**Comment by mrkno** [comment]
@phillipadsmith thinking about this, the easiest approach is to install to a node_modules directory inside each module (rather than the global one). This allows each module to manage its own dependencies without conflicts from the global node_modules.
Changes to make:
- When installing, install to module directory if a package.json exists (run `npm install --global --prefix <path to package.json>`)
- Update resolve to be able to search each module directory for dependencies
- Update `kpm` to perform an `npm update --global --prefix <package.json path>`

**Comment by phillipadsmith** [comment]
>  This allows each module to manage its own dependencies without conflicts from the global node_modules.

As you point out above, not a huge problem given that one can manually install the required modules. However, it would be great to include the modules dependencies right with the module for obvious reasons, i.e., not having to say in the README "be sure to install x, y, and z before installing this Concierge module"
